http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      service: app
    grafana:
      rule: "PathPrefix(`/grafana`)"
      service: grafana
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app-under-test:8000"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

entryPoints:
  web:
    address: ":80"

api:
  insecure: true
