modules:
  coordinator_llm:
    type: llm
    responses:
      need_action: [0.7, 0.2, 0.1]
      plan_review: [0.2, 0.5, 0.3]
    default: [0.3, 0.4, 0.3]
    confidence: 0.65
  delegation_critic:
    type: critic
    gain: 0.9
