modules:
  market_signal_analyst:
    type: analytics
    weights: [0.15, -0.05, 0.2, 0.1, 0.0, 0.3]
    bias: 0.02
    threshold: 0.01
  risk_adjusted_analyst:
    type: analytics
    weights: [0.05, 0.12, -0.08, 0.04, 0.09, 0.11]
    bias: -0.01
    threshold: 0.05
