receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: app
          scrape_interval: 15s
          static_configs:
            - targets: ["app-under-test:8000"]

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

exporters:
  logging:
    loglevel: info
  prometheus:
    endpoint: 0.0.0.0:8889
  otlphttp:
    endpoint: http://grafana:4318
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus, otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
