name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[qa]'
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy .
      - name: Bandit
        run: bandit -r .

  tests:
    name: Unit tests with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[qa]'
      - name: Pytest
        run: |
          pytest --cov-report=xml --cov-report=term-missing

